Vagrant.configure("2") do |config|
 config.vm.define "jenkins" do |subconfig|
   subconfig.vm.box = "sbeliakou/centos-7.4-x86_64-minimal"
    subconfig.vm.hostname = "jenkins"
     subconfig.vm.network :private_network, ip: "192.168.56.101"
      subconfig.vm.provision :shell, :path => "./vagrant.sh"
   config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
v.name="jenkins"
   
 end
end
end
